### ISSUE TITLE
Unconventional message format

### ISSUE THREAD

**Issue by matyasfodor** [DD-DeCaF/iloop-to-model#48]
The response from [this endpoint](https://github.com/DD-DeCaF/iloop-to-model/blob/devel/iloop_to_model/app.py#L272) resembles the one we receive from model service, but it is a bit different:
`growthRate` should be `growth-rate` (the best would be to update it in model service, use camelCase if possible)
added and removed reactions are missing although they are included in the messages.

Is it possible to add them?

**Comment by matyasfodor** [comment]
@sgalkina I assigned to you because I remember you were working on this service. Feel free to pass it over if you don't have time.

**Comment by siddC** [comment]
Hi Matyas, just a bit curious, but why should `growthRate` be `growth-rate`? Is it necessary for the service? Or just for consistency in naming convention?

**Comment by matyasfodor** [comment]
@siddC We use it as growth-rate in the model service: https://github.com/DD-DeCaF/model/blob/3767fbbc65208019cae1c5645f1b7c28ad9e9e57/model/constants.py#L66 and this causes duplication in the frontend: https://github.com/DD-DeCaF/metabolica-ui-map/blob/master/src/pathwayvis/components/map/map.component.ts#L311-L336

**Comment by matyasfodor** [comment]
I'd rather go with `growthRate` in both services, for all message keys, but I dont' know how much work that'd be

**Comment by kvikshaug** [comment]
This likely won't be fixed in this project so I'm closing the issue, but I've [added a card](https://app.zenhub.com/workspace/o/dd-decaf/scrum/issues/414) to come to a decision on casing, set it in the guidelines and then try to follow it consistently in all relevant services.
